### ISSUE TITLE
Demo: Dockerize

### ISSUE THREAD

**Issue by christophe-laprudence-howest** [MLoth/afsd-2023#28]
# Dockerize 

⚠️ Before you start, make sure that the API and PWA are building locally. Do this by running `npm run build` for both packages (workspaces).

## docker-compose-production.yml
Create a new `docker-compose` file in the infrastructure folder called `docker-compose-production.yml`. This file is intended for production use.

This file will descripe 2 extra services. A first for the **api** and a second service for the **pwa**.

The basic structure of this `docker-compose` file is similar to the one for development, but with the value of the name changed to *api-birds-production*.

### DB service
- As you can see the mongodb service has changed. 
  - The name of the named volume is different to avoid interference with the persistent storage of the development workflow.

### API service
- There's a new api service that uses a Dockerfile for building. The image is built in three steps / stages:

#### STEP 1 - Stage 1
In this step:
- The build context is set to the root folder of the monorepo.
- The `node:alpine` image is use.
-  If the Alpine image is not sufficient, for example, if one of the Node modules relies on Python, you can choose to use a version of Node.js where Python is included.
- The working directory inside this image is set to `/user/src/app`.
  - So, in the next lines, you'll copy everything to `/usr/src/app`. This will become the 'root' folder in the image, and you can use `./` to refer to it from now on."
- In the next step you copy some files to the image. 
  - `package*.json` files are copied from the monorepo to `/user/src/app`.
  - `package*.json` from `/packages/api` is copied to `/user/src/app/packages/api/` with `--chown=node:node`.
- `npm ci` is run to install the node modules.
  - At this point, all dependencies, including both development and production dependencies, are installed
- Now that the node modules are installed it's time to copy the **sourcecode**
  - The Source code from `/packages/api` is copied to the image.
- The `USER` instruction sets the default user for the current stage.
  - The `USER` instruction sets the user name (or UID) and optionally the user group (or GID) to use as the **default user** and group for the remainder of the current stage.

Use Docker Desktop to check if all the **necessary files** are copied inside the image. And all the **unnecessary files** are not copied inside the image.
- As you can see, some files are copied that shouldn't be copied. 💣
  - The `node_modules` folder is copied. This is not necessary because we will install the node_modules
  - The `dist` folder is copied. This is not necessary because we will build the dist folder.
  - The `.git` folder is copied. This is not necessary because we will not use git in the image.
  - The `.vscode` folder is copied. This is not necessary because we will not use vscode in the image.
  - The `.DS_Store` file is copied.
  - The .env file is copied. This is dangerous because it contains secrets. 
    - We will not use the .env file in the image. We will use environment variables instead.
  - ... etc

- 🎉 Add all of those files to the `.dockerignore` file and rerun the docker-compose command.

- Proceed to the next step / stage if you are sure that the files are copied without any errors.

#### STEP 2 - Stage 2

In the second step:
- `package*.json` files are copied to `/usr/src/app` in the image.
- The `node_modules` directory from the **development stage** is copied.
  - In order to run `npm run build` we need access to the Nest CLI which is a dev dependency. In the previous development stage we ran `npm ci` which installed all dependencies, so we can copy over the node_modules directory from the **development stage** 
- Source code of the API is copied to the image for building.
- Now clear the `node_modules` folder. And install only the **production dependencies**.
  - Set the `NODE_ENV` to `production`. 
  - Running `npm ci` removes the existing node_modules directory and passing in `--only=production` ensures that only the production dependencies are installed. This ensures that the node_modules directory is as optimized as possible

- Proceed to the next step / stage if you are sure that the files are copied without any errors.

#### STEP 3 - Stage 3
- In the last step.
  - `node_modules` and `dist` folders are copied from the previous stage to the current stage.

When examining the container's logs, you might notice our Firebase-related error. This is because the .json file wasn't copied into the image. We chose to keep this file outside the container.

## Use a secret in Docker
[Use Secrets in Compose](https://docs.docker.com/engine/swarm/secrets/#use-secrets-in-compose)

- Create a secret named `my-google-secret` in `docker-compose`. This secret is a file.
- Add the secret to the API service to grant it access.
- The file is mapped, **not** copied, to the folder `/run/secrets/` 
  - So you can use this path in an environment variable.

## PWA service 
This Dockerfile is a lot simpler. 
- The `node` image is used for the build stage.
- The `nginx` image is used for the production stage.
  - The `dist` folder from the build stage is copied to the production stage.
  - The `nginx.conf` file is copied to `/etc/nginx/conf.d/default.conf` in the `nginx` folder.

[Vue.js Deployment with Docker and Nginx](https://cli.vuejs.org/guide/deployment.html#docker-nginx)

# .dockerignore
Keep in mind to use `.dockerignore` to exclude files that are unnecessary for the image, such as `.git`, `.vscode`, `node_modules`, `dist`, `.env`, and more.

# Documentation
Don't forget to update the documentation so that the other developers know which .env variables they need to set in `.env.production.local` in order to run the application in Docker production.

**Comment by JarneDel** [comment]
Voor mensen die deze error krijgen
```
[Nest] 1 - 10/17/2023, 6:24:07 PM  ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
2023-10-17T18:24:07.300398972Z MongoServerSelectionError: getaddrinfo ENOTFOUND sportdb}
```
Na heel wat zoeken heb ik hier een oplossing voor gevonden:


```ts
// app.module.ts
@Module({
  imports: [
    ...,
    TypeOrmModule.forRoot({
      type: 'mongodb',
      url: `mongodb://${process.env.DB_HOST}:${process.env.DB_PORT}`, // database name verwijderen van deze lijn
      database: process.env.DB_NAME ?? 'api', // database hier toevogen
      entities: [__dirname + '/**/*.entity.{js,ts}'],
      synchronize: process.env.NODE_ENV != 'production', // Careful with this in production
      useNewUrlParser: true,
      useUnifiedTopology: true, // Disable deprecated warnings
      directConnection: true, // blijkbaar helpt dit
    }),
    ...
  ]})
```
